# @package _global_
model:
  name: fasterrcnn_resnet50
  pretrained: True
  get_fct: src.utils.get_model.get_od_model
  classes_reader: src.lightning_classes.LitOD
  backbone:
    class_name: torchvision.models.detection.fasterrcnn_resnet50_fpn
    params:
      pretrained: ${model.pretrained}
      num_classes: 91
      pretrained_backbone: True
      box_detections_per_img: 1000
    head:
      class_name: torchvision.models.detection.faster_rcnn.FastRCNNPredictor