defaults:
  - model: inception
  - training: default_training
  - optimizer: adamw
  - callbacks: default_callbacks
  - scheduler: plateau
  - dataset: test_ci_classification_dataset
  - augmentation: basic_augmentation_segmentation  # FIXME adapt for classification
  - tracker: # set logger here or use command line (e.g. `python GDL.py tracker=mlflow`)
  - inference: default_inference
  - hydra: default
  - override hydra/hydra_logging: colorlog # enable color logging to make it pretty
  - override hydra/job_logging: colorlog # enable color logging to make it pretty
  - _self_

general:
  # path to original working directory
  # hydra hijacks working directory by changing it to the current log directory,
  # so it's useful to have this path as a special variable
  # learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
  task: classification
  work_dir: ${hydra:runtime.cwd}  # where the code is executed
  config_name: ${hydra:job.config_name}
  config_override_dirname: ${hydra:job.override_dirname}
  config_path: ${hydra:runtime.config_sources}
  project_name: template_project
  workspace: your_name
  device: cuda
  max_epochs: 2 # for train only
  min_epochs: 1 # for train only
  raw_data_dir: ${general.work_dir}/data
  raw_data_csv: ${general.work_dir}/data/inference_classif_ci_csv.csv  # used for inference only
  sample_data_dir:
  state_dict_path:
  save_weights_dir: ${general.work_dir}/weights_saved

AWS:
  bucket_name:

print_config: True # save the config in the log folder
mode: {sampling, train, evaluate, inference, hyperparameters_search}
debug: False # will print the complete yaml config plus run a validation test
