# lightning.pytorch==2.3.2
seed_everything: true

trainer:
  accelerator: "gpu"
  devices: -1
  strategy: "ddp"
  logger:
    class_path: lightning.pytorch.loggers.mlflow.MLFlowLogger
    init_args:
      save_dir: /home/valhassa/Projects/geo-deep-learning/logs
      experiment_name: "gdl_experiment"
      run_name: "gdl_run"
  max_epochs: 10
  min_epochs: 2
ckpt_path: null

model:
  class_path: tasks_with_models.segmentation_segformer.SegmentationSegformer
  init_args:
    encoder: "mit_b0"
    in_channels: 3
    num_classes: 5
    loss: 
      class_path: segmentation_models_pytorch.losses.DiceLoss
      init_args:
        mode: "multiclass"
    class_labels: ["background", "fore", "hydro", "roads", "buildings"]

optimizer:
  class_path: Adam
  init_args:
    lr: 0.001

lr_scheduler: 
  class_path: ReduceLROnPlateau
  init_args:
    monitor: "val_loss"
    mode: "min"
    factor: 0.1
    patience: 2

data:
  class_path: datamodules.imagery_NonGeoDataModule.BlueSkyNonGeoDataModule
  init_args:
    batch_size: 16
    num_workers: 8
    data_type_max: 255
    patch_size:
    - 512
    - 512
    mean:
    - 0.0
    - 0.0
    - 0.0
    std:
    - 1.0
    - 1.0
    - 1.0
    csv_root_folder: /export/sata01/wspace/test_dir/multi/all_rgb_data/patches/4cls_RGB
    patches_root_folder: /export/sata01/wspace/test_dir/multi/all_rgb_data/patches/4cls_RGB
