seed_everything: true

trainer:
  accelerator: "gpu"
  devices: -1
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
      gradient_as_bucket_view: true
      static_graph: true
  gradient_clip_val: 1.0
  precision: "16-mixed"
  sync_batchnorm: true
  logger:
    class_path: lightning.pytorch.loggers.mlflow.MLFlowLogger
    init_args:
      save_dir: /home/valhassa/Projects/geo-deep-learning/logs
      log_model: all
      experiment_name: "gdl_experiment"
      run_name: "segformer_mit_b0"
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        mode: "min"
        verbose: False
        patience: 20
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        mode: "min"
        save_top_k: 1
        filename: "model-{epoch:02d}-{val_loss:.3f}"
    - class_path: tools.callbacks.segmentation_visualization.VisualizationCallback
      init_args:
        max_samples: 3
  max_epochs: 10

model:
  class_path: tasks_with_models.segmentation_segformer.SegmentationSegformer
  init_args:
    encoder: "mit_b0" # "mit_b0", "mit_b1", "mit_b2", "mit_b3", "mit_b4", "mit_b5"
    image_size: [512, 512]
    in_channels: 3
    weights: imagenet
    max_samples: 6
    num_classes: 5
    freeze_layers: null
    use_dynamic_encoder: false
    loss:
      class_path: segmentation_models_pytorch.losses.DiceLoss
      init_args:
        mode: "multiclass"
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 6e-5
    scheduler:
      class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
      init_args:
        mode: "min"
        factor: 0.1
        patience: 10
        cooldown: 1
        min_lr: 6e-8
    scheduler_config:
      interval: "epoch"
      frequency: 1
      monitor: "val_loss"
    class_labels: ["background", "fore", "hydro", "roads", "buildings"]
    class_colors: ["#000000", "#008000", "#0000FF", "#FFFF00", "#FF0000"]
    weights_from_checkpoint_path: null

data:
  class_path: datamodules.csv_datamodule.CSVDataModule
  init_args:
    batch_size: 4
    num_workers: 8
    data_type_max: 255
    patch_size:
    - 512
    - 512
    mean:
    - 0.3992
    - 0.4283
    - 0.3998
    std:
    - 0.1672
    - 0.1800
    - 0.1584
    csv_root_folder: /export/sata01/wspace/test_dir/multi/all_rgb_data/patches/4cls_RGB
    patches_root_folder: /export/sata01/wspace/test_dir/multi/all_rgb_data/patches/4cls_RGB

ckpt_path: null
