seed_everything: true

trainer:
  accelerator: "gpu"
  devices: -1
  strategy: ddp
  precision: "bf16-mixed"
  gradient_clip_val: 1.0
  sync_batchnorm: true
  logger:
    class_path: tools.loggers.overrideStepEpochsMlflowLogger.OverrideStepEpochsMlflowLogger
    init_args:
      save_dir: /gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/DA_SAR_FLOOD/sar_water_extraction/mlruns
      log_model: all
      experiment_name: "softbce"
      run_name: "unet_${model.init_args.encoder}_sentinel"
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        mode: "min"
        verbose: False
        patience: 30
        check_on_train_epoch_end: True
        log_rank_zero_only: True
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        mode: "min"
        save_top_k: 1
        filename: "model-{epoch:02d}-{val_loss:.3f}"
    - class_path: tools.callbacks.segmentation_visualization.VisualizationCallback
      init_args:
        max_samples: 15
        mean: ${data.init_args.mean}
        std: ${data.init_args.std}
        data_type_max: ${data.init_args.data_type_max}
        num_classes: ${model.init_args.num_classes}
        class_colors: ${model.init_args.class_colors}
    - class_path: tools.callbacks.overrideEpochStepsCallback.OverrideEpochStepCallback
      init_args:
        override: true
  max_epochs: 200

model:
  class_path: tasks_with_models.segmentation_unet.SegmentationUnet
  init_args:
    encoder: "resnet101"
    weights: imagenet
    in_channels: 4 #5
    max_samples: 50
    num_classes: 2
    mean: ${data.init_args.mean}
    std: ${data.init_args.std}
    data_type_max: ${data.init_args.data_type_max}
    lr: 1e-4
    class_weight: 2
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 1e-4
    # scheduler:
    #   class_path: torch.optim.lr_scheduler.OnceCycleLR
    #   init_args:
    #     max_lr: 1e-3
    #     epochs: ${trainer.max_epochs}
    #     pct_start: 0.3
    scheduler_config:
      interval: "epoch"
      frequency: 1
      monitor: "val_loss"
    weight_decay: 4e-5
    class_labels: ["background", "water"]
    class_colors: ["#000000", "#0000FF"]
    weights_from_checkpoint_path:
data:
  class_path: datamodules.SAR_FloodAsWaterDataModule.SarWaterNonGeoDataModule
  init_args:
    batch_size: 32
    num_workers: 8
    data_type_max: 1
    noData: 255
    band_indices: [0, 1, 2, 3]
    patch_size:
    - 512
    - 512
    mean:
    - 0.1521
    - 0.1769
    - 0.1325
    - 0.2922
    - 0.2101
    std:
    - 0.1240
    - 0.1282
    - 0.1077
    - 0.2032
    - 0.1175
    csv_root_folder: /gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/DA_SAR_FLOOD/sar_water_extraction/data/datasets/Sentinel/patches/Sentinel
    patches_root_folder: /gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/DA_SAR_FLOOD/sar_water_extraction/data/datasets/Sentinel/patches/Sentinel

ckpt_path: null