# @package _global_
dataset:
  # dataset-wide
  name:
  raw_data_csv: ${general.raw_data_csv}
  raw_data_dir: ${general.raw_data_dir}
  download_data: False

  # imagery
  bands: [red,green,blue]
  dsm_dir: null

  # ground truth
  attribute_field: properties/class
  attribute_values: [1]
  class_name: # will follow in the next version
  classes_dict: {'WAER':1, 'FORE':2, 'ROAI':3, 'BUIL':4}
  class_weights:
  ignore_index: 255
