# @package _global_
dataset:
  # dataset-wide
  name:
  use_stratification: False
  train_val_percent: {'trn':0.7, 'val':0.3, 'tst':0}
  raw_data_csv: tests/tiling/tiling_segmentation_binary-stac_ci.csv
  raw_data_dir: ${general.raw_data_dir}
  download_data: False

  # imagery
  bands: [red, green, blue]

  # ground truth
  attribute_field:
  attribute_values:
  min_annotated_percent: ${tiling.min_annot_perc}
  class_name: # will follow in the next version
  classes_dict: {'BUIL':1}
  class_weights:
  ignore_index: -1

  # outputs
  tiles_data_dir: ${general.tiles_data_dir}

