# @package _global_
dataset:
  # dataset-wide
  name:
  use_stratification: False
  train_val_percent: {'trn':0.7, 'val':0.2, 'tst':0.1}
  raw_data_csv: ${general.raw_data_csv}
  raw_data_dir: ${general.raw_data_dir}
  validate_data: True

  # imagery
  in_bands: ['B','G','R']
  out_modalities: ['R','G','B']

  # ground truth
  attribute_field: "class"
  attribute_vals: 1
  min_annot_perc:
  class_name: # will follow in the next version
  classes_dict: {'Building':1}
  class_weights:
  ignore_index: -1

  # outputs
  tiles_data_dir: ${general.tiles_data_dir}