# @package _global_
dataset:
  name:
  in_bands: ['B','G','R']
  out_modalities: ['R','G','B']
  raw_data_csv: ${general.raw_data_csv}
  raw_data_dir: ${general.raw_data_dir}
  tiles_data_dir: ${general.tiles_data_dir}
  class_name: # will follow in the next version
  classes_dict: {'Building':1}
  class_weights:
  train_val_percent: {'trn':0.5, 'val':0.4, 'tst':0.1}
  attribute_field: "class"
  attribute_vals: 1
  validate_data: True
  ignore_index:
